# This is a basic workflow to help you get started with Actions
# Source: https://github.com/abarichello/godot-ci/blob/master/.github/workflows/godot-ci.yml
name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: ["main", "test-ci"]

env:
    GODOT_VERSION: 4.2.1
    EXPORT_NAME: Roguenoid

jobs:
    export-web:
        name: Web Export
        runs-on: ubuntu-20.04
        container:
            image: barichello/godot-ci:4.2.1
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  lfs: true
            - name: Setup
              run: |
                  mkdir -v -p ~/.local/share/godot/export_templates/
                  mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
            - name: Web Build
              run: |
                  mkdir -v -p .build/web
                  godot --headless --verbose --export-release "Web" .build/web/index.html
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: web
                  path: .build/web
            - name: Install rsync 📚
              run: |
                  apt-get update && apt-get install -y rsync
            - name: Deploy to GitHub Pages 🚀
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: .build/web # The folder the action should deploy.
